// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller.js"
application.register("address-autocomplete", AddressAutocompleteController)

import CreateGroupController from "./create_group_controller.js"
application.register("create-group", CreateGroupController)

import MapController from "./map_controller.js"
application.register("map", MapController)

import Select2Controller from "./select2_controller.js"
application.register("select2", Select2Controller)

import SelectEventController from "./select_event_controller.js"
application.register("select-event", SelectEventController)

import SwitchTabsController from "./switch_tabs_controller.js"
application.register("switch-tabs", SwitchTabsController)
